apiVersion: v1
kind: Config
clusters:
- cluster:
    certificate-authority-data: <CA_CERT_BASE64>
    server: https://<TAILSCALE_IP>:6443
  name: homelab
contexts:
- context:
    cluster: homelab
    user: alif-homelab
  name: homelab-context
current-context: homelab-context
users:
- name: alif-homelab
  user:
    client-certificate-data: <CLIENT_CERT_BASE64>
    client-key-data: <CLIENT_KEY_BASE64>
